apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hungry-panda
  description: Tanzu Java Spring-Boot Web App, displaying kubernetes info on '/k8s' endpoint. Written by Guy Balmas.
  tags:
  - app-accelerator
  - java-17
  - spring
  - web
  - tanzu
  - kubernetes
  - guy
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=hungry-panda
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://guy-example-web-app.apps.guy-tap.terasky.demo/hello/
    name: Hello-World
  - url: https://guy-example-web-app.apps.guy-tap.terasky.demo/hello/welcome
    name: Welcome
  - url: https://guy-example-web-app.apps.guy-tap.terasky.demo/k8s/
    name: K8S-spec
spec:
  type: service
  lifecycle: experimental
  owner: cloud-native-applications-team
  system: hungry-pandas
  providesApis:
  - apps/hungry-panda-dev
