apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cloud-native-applications-team
spec:
  type: team
  profile:
    displayName: Cloud Native Applications Team
    email: cna-team@example.com
    # picture: https://example.com/groups/cloud-native-applications-team.jpeg
  parent: development
  children: []
  members: [default/guybal]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
spec:
  type: department
  profile:
    displayName: Development Department
    email: development@example.com
    # picture: https://example.com/groups/development.jpeg
  children: 
    - cloud-native-applications-team
