# team.yaml
apiVersion: backstage.io/v1alpha1
kind: Team
metadata:
  name: cloud-native-applications-team
spec:
  name: Cloud Native Applications Team
  description: Team responsible for developing cloud-native applications

# system.yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: hungry-pandas
spec:
  owner: cloud-native-applications-team
  type: application
  lifecycle: experimental
  description: Hungry Pandas application system

# domain.yaml
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: apps
spec:
  owner: cloud-native-applications-team
  type: business
  lifecycle: experimental
  description: Business domain for cloud-native applications

# database-service.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: database-service
  description: Database service for the Hungry Panda application
  annotations:
    backstage.io/managed-by: database-team
    backstage.io/system: hungry-pandas
spec:
  type: service
  lifecycle: experimental
  owner: database-team

# hungry-panda-dev.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hungry-panda-dev
  description: Backend service for the Hungry Panda application
  annotations:
    backstage.io/managed-by: cloud-native-applications-team
    backstage.io/system: hungry-pandas
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://hungry-panda.apps.guy-tkg-tap1-cls.terasky.demo/hello/
    name: Hello-World
  - url: https://hungry-panda.apps.guy-tkg-tap1-cls.terasky.demo/hello/welcome
    name: Welcome
  - url: https://hungry-panda.apps.guy-tkg-tap1-cls.terasky.demo/k8s/
    name: K8S-spec
spec:
  type: service
  lifecycle: experimental
  providesApis:
    - kind: service
      target: apps/hungry-panda-dev
  owner: cloud-native-applications-team
  providesResources:
    - kind: api
      name: hungry-panda-dev-api
      description: REST API for the Hungry Panda application
      spec:
        type: rest
        lifecycle: experimental
        schema: openapi.yaml
  dependencies:
    - kind: component
      name: database-service
      relations:
        - type: uses
          target: database-service.postgresql
