apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guybal
spec:
  profile:
    displayName: Guy Balmas
    email: guyb@terasky.com
    # picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf:
    - cloud-native-applications-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cloud-native-applications-team
spec:
  type: team
  profile:
    displayName: Cloud Native Applications Team
    email: cna-team@example.com
    # picture: https://example.com/groups/cloud-native-applications-team.jpeg
  parent: development
  children: []
  members:
    - guybal
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
spec:
  type: department
  profile:
    displayName: Development Department
    email: development@example.com
    # picture: https://example.com/groups/development.jpeg
  children:
    - cloud-native-applications-team
---
# system.yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: hungry-pandas
spec:
  owner: cloud-native-applications-team
  type: application
  lifecycle: experimental
  description: Hungry Pandas Application
---
# databases-domain.yaml
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: databases
spec:
  owner: database-team
  type: technical
  lifecycle: experimental
  description: Domain for managing databases
---
# domain.yaml
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: apps
spec:
  owner: cloud-native-applications-team
  type: business
  lifecycle: experimental
  description: Business domain for cloud-native applications
---
# database-service.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: database-service
  description: Database service for the Hungry Panda application
  annotations:
    backstage.io/managed-by: database-team
    backstage.io/system: hungry-pandas
    backstage.io/domain: databases
spec:
  type: service
  lifecycle: experimental
  owner: database-team
  system: hungry-pandas
---
# hungry-panda-dev.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hungry-panda-dev
  description: Backend service for the Hungry Panda application
  annotations:
    backstage.io/managed-by: cloud-native-applications-team
    backstage.io/system: hungry-pandas
    backstage.io/domain: apps
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=hungry-panda
  links:
  - url: https://hungry-panda.apps.guy-tkg-tap1-cls.terasky.demo/hello/
    name: Hello-World
  - url: https://hungry-panda.apps.guy-tkg-tap1-cls.terasky.demo/hello/welcome
    name: Welcome
  - url: https://hungry-panda.apps.guy-tkg-tap1-cls.terasky.demo/k8s/
    name: K8S-spec
spec:
  type: service
  lifecycle: experimental
  providesApis: 
    - "apps/hungry-panda-dev"
  owner: cloud-native-applications-team
  system: hungry-pandas
  providesResources:
    - kind: api
      name: hungry-panda-dev-api
      description: REST API for the Hungry Panda application
      spec:
        type: rest
        lifecycle: experimental
        schema: openapi.yaml
  dependencies:
    - kind: component
      name: database-service
      relations:
        - type: uses
          target: database-service.postgresql
